import type { NextPage } from 'next'
import Head from 'next/head'
import FrontPage from '../componenets/FrontPage'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>To You From Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FrontPage />
    </div>
  )
}

export default Home
